# TODO  clean this upand remove Excludes not needed.

# Rubocop extensions
require:
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude  # Merge my AllCops.Exclude with default exludes from https://github.com/rubocop/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 3.1
  UseCache: true
  Include:
  - lib/**/*.rb
  - test/**/*.rb

Gemspec/DateAssignment:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
  Exclude:
  - lib/nestedtext-ruby/errors_internal.rb
Lint/EmptyInPattern:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Layout/LineLength:
  Max: 120
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UnreachableCode:
  Severity: error
Lint/UselessAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
Metrics/BlockLength:
  Enabled: true
  Max: 100
Metrics/MethodLength:
  Enabled: true
  Max: 25

Naming/FileName:
  Enabled: false
  Exclude:
  - lib/nestedtext-ruby.rb
Naming/InclusiveLanguage:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/Documentation:
  Enabled: true
  Exclude:
  - lib/nestedtext-ruby/errors_internal.rb
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false
Style/SingleLineMethods:
  Enabled: true
  Exclude:
  - lib/nestedtext-ruby/errors_internal.rb
Style/StringChars:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Style/SwapValues:
  Enabled: true


# Reference: https://github.com/rubocop/rubocop-rake/blob/master/config/default.yml
Rake:
  Enabled: true
