name: Continuous Deployment   # Well, semi-continuous

# TODO should depend on successful ci.yml
on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: bundle exec rake release

# TODO publish to GitHub packages as well. using also same conditionss as gem.
