name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/cd.yml'
      - '.github/workflows/codeql-analysis.yml'
  pull_request:
    branches: [ main]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/cd.yml'
      - '.github/workflows/codeql-analysis.yml'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      codeclimate: true
