name: Continuous Integration

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main]
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        # os: [ubuntu, macos, windows]
        #ruby-version: [2.7, 3.1]
        ruby-version: ['3.1']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run rake cibuild
      run: bundle exec rake cibuild
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      #if: matrix.ruby_version == '3.1' && github.event_name != 'pull_request'
      env:
        CC_TEST_REPORTER_ID: 031d4b3d619508ecf0f2d6ce8f2565d506d4cb24b6fa7ef913af274533021bee
      with:
        debug: true
