name: Continuous Integration

on:
  workflow_dispatch:
    branches: main
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/cd.yml'
      - '.github/workflows/codeql-analysis.yml'
      - 'lib/nestedtext/version.rb'  # Avoid CI when CD will trigger and do the same testing.
  pull_request:
    branches: [ main]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/cd.yml'
      - '.github/workflows/codeql-analysis.yml'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      code_coverage: true
