name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  cibuild:
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        # os: [ubuntu, macos, windows]
        #ruby-version: [2.7, 3.1]
        ruby-version: [3.1]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run cibuild
      run: bundle exec rake cibuild
